### ISSUE TITLE
Reviewboard tool repo missing the ini file

### ISSUE THREAD

**Issue by vogxn** [CloudStack-extras/reviewboard-tools#1]
The ini. properties file from where config params are read to check_reviews() is missing the repo. A format of the properties file needs to be checked in hiding sensitive information.

**Comment by spark404** [comment]
Fixed with commit 116ef942279db59cb275e47f427fc1479df4bbcd

**Comment by CloudDotCom** [comment]
Hi all,

Any idea how this alias was set up? It's going to my @Citrix.com address
rather than my @apache.org or @zonker.net address, which is vastly,
greatly, massively preferred.

Thanks!

Joe
